package com.oau.nhif.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;

/**
 * Simple request model for card authorization without biometric verification
 */
@Getter
@Setter
public class SimpleCardAuthorizationRequest {
    @JsonProperty("cardNo")
    private String cardNo;
    
    @JsonProperty("visitTypeID")
    private int visitTypeID;
    
    @JsonProperty("referralNo")
    private String referralNo;
    
    @JsonProperty("remarks")
    private String remarks;

    @JsonProperty("nationalID")
    private String nationalID;
    
    // Constructors
    public SimpleCardAuthorizationRequest() {}
    
    public SimpleCardAuthorizationRequest(String cardNo, int visitTypeID) {
        this.cardNo = cardNo;
        this.visitTypeID = visitTypeID;
    }
    
    public SimpleCardAuthorizationRequest(String cardNo, int visitTypeID, String referralNo, String remarks) {
        this.cardNo = cardNo;
        this.visitTypeID = visitTypeID;
        this.referralNo = referralNo;
        this.remarks = remarks;
    }

    public SimpleCardAuthorizationRequest(String cardNo, int visitTypeID, String referralNo, String remarks, String nationalID) {
        this.cardNo = cardNo;
        this.visitTypeID = visitTypeID;
        if(referralNo != null && !referralNo.isEmpty()) {
            this.referralNo = referralNo;
        }
        this.remarks = remarks;
        this.nationalID = nationalID;
    }
    
    // Getters and setters are automatically generated by Lombok's @Getter and @Setter annotations
}